### PR TITLE
default attribute added

### PR DESCRIPTION
**Pull request by effect01**
a very useful option to not be redundant in your json :D

### CODE REVIEW

**Comment by TimoBechtel** [comment]
Thank you for your contribution!

Do you have an example on where this feature is useful?

I think changing the behavior, when `default` is used as property, might be unexpected. (Not to mention, this will introduce a breaking change).
We could use something like `__default` instead of `default` to differentiate it a little more, but I don't know yet how useful this feature is.

**Comment by effect01** [comment]
__default sound good aswell. In my case I want use ant design, and bootstrap (or other like that) with the same variables, but some case exits, for example: --blue and --blue-secundary. 

{ 
 blue: #color1,
 blue : { 
    primary: #color2
  } 
 } // --blue , --blue-primary

with the default if 
{ 
   blue : { 
   __default: #color1
   primary: #color2
   } 
 }  // --blue , --blue-primary

**Comment by effect01** [comment]
other example 
...
  primary: {
    light: `lighten(${blue.primary} 40%)`,
    opacity: `rgba(${blue.primary}, 0.2)`,
    default: blue.primary
  },
  secondary: {
    light: `lighten(#ac39d4, 44%)`,
    opacity: `rgba(#ac39d4, 0.5)`,
    default: `#ac39d4`
  },

**Comment by TimoBechtel** [comment]
I can see how this is useful, especially with the second example.
I added a few notes about this and a test case. 

Will merge this shortly.

Note: You can surround your code examples with triple backticks (\`\`\`) on GitHub to make it a little more readable :)

**Comment by effect01** [comment]
oh ty for your tips 👍 
```
console.log("...learning how to use this")
> "...learning how to use this"

```

**Pull request merged**
